### ISSUE TITLE
Including PDFs into the sitemap

### ISSUE THREAD

**Issue by 5wes13** [wilr/silverstripe-googlesitemaps#159]
This is feature request instead of an issue. Are there any plans to include PDFs into the sitemaps at all? We have a ton of manuals and documents associated with our products and would be great if we could tell search engines when new documentations have been added.

**Comment by wilr** [comment]
@5wes13 you can already do this (see https://github.com/wilr/silverstripe-googlesitemaps/blob/master/docs/en/index.md#including-dataobjects)

If your PDF's are listed as File records then just add the following to a `config.yml` file (untested but should work).

```
Wilr\GoogleSitemaps\GoogleSitemap:
  dataobjects:
    - SilverStripe\Assets\File:
      frequency: 'daily'
SilverStripe\Assets\File:
  extensions:
    - Wilr\GoogleSitemaps\Extensions\GoogleSitemapExtension
```
