### ISSUE TITLE
Sitemap empty in 3.1

### ISSUE THREAD

**Issue by frankmullenger** [wilr/silverstripe-googlesitemaps#49]
With about 4 published pages (included in search) the `$sitemaps` ArrayList appears empty for me at this point:
https://github.com/silverstripe-labs/silverstripe-googlesitemaps/blob/master/code/GoogleSitemap.php#L286

Using this configuration:

``` yaml

---
Name: customgooglesitemaps
After: googlesitemaps

---
GoogleSitemap:
    enabled: true
    objects_per_sitemap: 999
    google_notification_enabled: false
    use_show_in_search: true
```

Using this version of SilverStripe:

```
silverstripe/cms             3.1.x-dev d65e5b6  The SilverStripe Content Management System
silverstripe/framework       3.1.x-dev d892629  The SilverStripe framework
```
